name: Deploy LFPR Prediction App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test application
      run: |
        python -c "import app; print('App imports successfully')"
    
    - name: Deploy to Heroku
      if: github.ref == 'refs/heads/main'
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: |
        # Install Heroku CLI
        curl https://cli-assets.heroku.com/install.sh | sh
        # Login and deploy
        echo "$HEROKU_API_KEY" | heroku auth:token
        heroku git:remote -a $HEROKU_APP_NAME
        git push heroku main
    
    - name: Deploy to Railway
      if: github.ref == 'refs/heads/main'
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        # Install Railway CLI
        npm install -g @railway/cli
        # Login and deploy
        railway login --token $RAILWAY_TOKEN
        railway up --detach
